### ISSUE TITLE
Detect Embedded N-Grams

### ISSUE THREAD

**Issue by crantila** [ELVIS-Project/vis-framework#214]
Quote from P.S.:
> … I'm looking at [a piece] and it says there's an 8-gram repeated twice but those 2 are
> part of a 10-gram! We've got to have an automated way of plugging in successively
> smaller values for n starting with the length of the piece minus one so we really get the
> longest. In this case it's a sequence and bits of it keep showing up all the way down to
> 2-grams. Another wish is that such sub-grams can be weeded out of lists that show
> many different values of n on a single page.

For the effort this is going to take, there are many more complicated features we should get from the same code. We can figure it out later.

**Comment by alexandermorgan** [comment]
I think this is the nature of chains that include internal repetition coupled with sliding-window analysis. I don't think this is worth the time it would take because even if we did it it would take more effort to describe the usefulness of the feature to users than it would to help researchers be more generally aware of what our results mean.

**Comment by crantila** [comment]
I know. There's a reason this was never even started. But it was a long-time fixation for Peter. Has he truly forgotten about it, or moved on?

**Comment by alexandermorgan** [comment]
I think we realized this embedded n-grams thing was not a direction we wanted to go in when I was working on Peter and Julie's 36-duet set study. There are currently no plans for this so I'm closing the issue.
