### ISSUE TITLE
Polyphonic Instruments

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#382]
Creation of being able to index polyphonic instruments (like a piano, harpsichord, harp, etc.).

**Comment by crantila** [comment]
I've been running piano music for years. What's this for?

**Comment by musicus** [comment]
Great. Perhaps something that should be added to the documentation, or the tutorial.

**Comment by crantila** [comment]
Are you having problems with a specific piece? Is this about knowing the music theory "voices" in a file that didn't encoded them separately?

**Comment by musicus** [comment]
The piano part has a variable amount of voices, and the piano part is not encoded into separate voices.

**Comment by crantila** [comment]
I worked on a series of VIS algorithms in July/August 2013 to help deal with weirdly encoded piano pieces like that. They didn't even live long enough to make it into a VIS 1.x release due to a lack of interest, so they pre-date the indexers-and-experimenters architecture. There should be something to extract the highest and lowest parts, and something to find verticalities/simultaneities too, if you want to go looking!

**Comment by musicus** [comment]
I always wanna look!

**Comment by mborsodi** [comment]
Is this issue the same as #258? If so, maybe we should close one of them just to avoid confusion? If not, what is the difference?

**Comment by alexandermorgan** [comment]
I'm reopenning this because this is getting addressed in my changes for VIS 3. The functionality is already in alex_devel but this should stay open until I'm done writing tests and merge it into master or at least develop. @musicus why was this issue closed in the first place? Generally it's good to say why you're closing an issue unless you close it with a commit, in which case the reason is obvious.

**Comment by musicus** [comment]
It seems as though I created the issue. I'll check alex_devel.

**Comment by alexandermorgan** [comment]
This is addressed in alex_devel as of commit 00382fb5e2d863498dcba30c1a4dcf19eabfa803 with the new experimental indexer: noterest.MultiStopIndexer
This isn't perfect but it is stable and a good first step towards a more complex, analysis-based solution. It doesn't guarantee the most musical partitioning of notes and rests into voices, but it does guarantee that all notes in the score show up in its resultant dataframe.

**Comment by alexandermorgan** [comment]
To address Marina's question, this issue is different from #258 in that getting the notes from a polyphonic instrument (or a part with a divisi) and then putting those notes into "parts" (more precisely separate columns in a dataframe) is distinct from assessing what chords those notes form at any given moment. Getting the notes (this issue) is pretty objective, whereas deciding what chords the form (issue #258) is somewhat subject, stylistically dependent, and just generally a much more complex task.
