### ISSUE TITLE
HorizontalIntervalIndexer

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#390]
When specifying a settings ('setts') parameter, all dictionary items work, except for the ```directed``` item. The ```directed``` item always evaluates to ```True```, even when set to ```False```.

**Comment by alexandermorgan** [comment]
@musicus That doesn't seem possible because all the default settings are updated with whatever settings the user passes, if any, at the same time in the same line of code. I don't see how it could work for some settings and not others. Are you sure you're using the right word? In an earlier version I the setting was called 'direction' but now you have to use the word 'directed' as noted in the docs.

**Comment by musicus** [comment]
Right? Seems implausible, but I tried multiple times, quadruple checked spelling, and that is the one that always evaluates as ```True```. :-/

**Comment by musicus** [comment]
Ha. I have an older version of the VIS-framework in my venv ... in which case I'll have to use the older spelling. This is a problem with renaming things and backwards compatibility. I'll try anew, and if all is good will close this issue...

**Comment by alexandermorgan** [comment]
Ok, why are you using an older version of VIS though?

**Comment by musicus** [comment]
It was one that was in my ```venv```, since I started the project I'm working on before you released a newer version.

**Comment by musicus** [comment]
Looks like I was using vis-framework 2.3.0 in my ```venv``` ... upgraded to 2.4.1: butter. However, what was the reasoning behind changing from ```direction``` to ```directed```? It certainly is bad far backward compatibility,

**Comment by alexandermorgan** [comment]
Fair enough. I think there was an issue where it appeared both ways before and was causing this problem. Also I think it was that it didn't make as much sense for "direction" to be true or false as it did for "directed".
