### ISSUE TITLE
dissonance indexer Documentation

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/vis-framework#428]
The dissonance indexer is well documented, and features plenty of docsting information. 

The docstring information should be formatted in such a way that sphinx will be able to pick it up.

However, it should feature code examples in its [```run()``` method](https://github.com/ELVIS-Project/vis-framework/blob/master/vis/analyzers/indexers/dissonance.py#L904) as other indexers do, and show anticipated outcomes with using an ```example.xml``` file from the [```vis/tests/corpus/```](https://github.com/ELVIS-Project/vis-framework/tree/master/vis/tests/corpus) directory.

**Comment by alexandermorgan** [comment]
The run() method is a bad place to put essential documentation because several indexers don't have one. This is why I've been moving the most important documentation out of the run methods of indexers. So I don't think this should be done. I'm also unassigning myself because the time to assign stuff to me has long passed, as I mentioned in my email a week or two ago.

**Comment by musicus** [comment]
That is besides the point, and you are avoiding the main issue: Where is the example code? Good documentation alway features example code along with its example output. 

I'm sorry, I asked on multiple occasions to ensure that everything is appropriately documented and it is not. I think it is your responsibility before you leave the project that everything is documented with example code and example outcome that will be picked up by sphinx. So whether it is in the run() method or not irrelevant.

**Comment by musicus** [comment]
Docstrings aligned with Sphinx, and code brought into pep8 compliance (mostly).
